# Generated by Django 4.0.1 on 2022-01-30 06:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfoodportion",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
