# Generated by Django 4.0.2 on 2022-03-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker', '0003_remove_userfoodmembership_name_remove_usermeal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdafnddsfood',
            name='usda_food',
            field=models.OneToOneField(help_text='USDA Food for this fndds food.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutrition_tracker.usdafood', verbose_name='usda_food'),
        ),
        migrations.AlterField(
            model_name='usdafoundationfood',
            name='usda_food',
            field=models.OneToOneField(help_text='USDA Food for this foundation food.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutrition_tracker.usdafood', verbose_name='usda_food'),
        ),
        migrations.AlterField(
            model_name='usdasrlegacy',
            name='usda_food',
            field=models.OneToOneField(help_text='USDA Food for this SR legacy food.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutrition_tracker.usdafood', verbose_name='usda_food'),
        ),
    ]
