# Generated by Django 4.0.4 on 2022-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker', '0004_alter_usdafnddsfood_usda_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdabrandedfood',
            name='package_weight',
            field=models.TextField(blank=True, help_text='Package weight.', null=True, verbose_name='package_weight'),
        ),
        migrations.AddField(
            model_name='usdabrandedfood',
            name='preparation_state_code',
            field=models.TextField(blank=True, help_text='Preparation state code.', null=True, verbose_name='preparation_state_code'),
        ),
        migrations.AddField(
            model_name='usdabrandedfood',
            name='trade_channel',
            field=models.TextField(blank=True, help_text='Trade channel.', null=True, verbose_name='trade_channel'),
        ),
        migrations.AddField(
            model_name='usdafoodnutrient',
            name='loq',
            field=models.TextField(blank=True, help_text='loq', null=True, verbose_name='loq'),
        ),
    ]
