# Generated by Django 4.0.4 on 2022-05-31 07:43

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker', '0005_usdabrandedfood_package_weight_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfoodmembership',
            constraint=models.CheckConstraint(check=models.Q(('parent_id', django.db.models.expressions.F('child_id')), ('parent_type', django.db.models.expressions.F('child_type')), _negated=True), name='nutrition_tracker_userfoodmembership_parent_child_different'),
        ),
    ]
